[[entries]]
id = "b473bf0d-3dd0-4577-806a-ac34b717ac7d"
type = "improvement"
description = "Look for `kraken.build.py` scripts in addition to `kraken.py`, the latter can result into issues resolving the `kraken` package as the build script can take precedence"
author = "@NiklasRosenstein"

[[entries]]
id = "c3d3f28b-cfc6-41ed-a4bb-78d91c2c4199"
type = "feature"
description = "add `Project.metadata` and `Project.find_metadata()` which can be used by plugins to store project-global data"
author = "@NiklasRosenstein"
