[[entries]]
id = "14d81259-6a70-4b91-88fa-5d397e5a0dad"
type = "improvement"
description = "`Project.do()` no longer overrides `Task.default` and `Task.capture` by default if no explicit value is specified"
author = "@NiklasRosenstein"
